import "server-only";

export const tags = [
  // Programming Languages
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Go",
  "Rust",
  "Scala",
  "Dart",
  "Perl",
  "Haskell",
  "Lua",
  "Clojure",
  "Elixir",
  "Erlang",
  "F#",
  "Julia",
  "Lisp",
  "Prolog",
  "R",
  "Matlab",
  "Fortran",
  "Cobol",
  "Ada",
  "Visual Basic",
  "Groovy",
  "Objective-C",
  "Assembly",

  // Web Development
  "HTML",
  "CSS",
  "Sass",
  "Less",
  "React",
  "Angular",
  "Vue.js",
  "Svelte",
  "Ember.js",
  "Backbone.js",
  "jQuery",
  "Redux",
  "Next.js",
  "Gatsby",
  "Express.js",
  "Koa",
  "Hapi",
  "Meteor",
  "Laravel",
  "Symfony",
  "Ruby on Rails",
  "Django",
  "Flask",
  "Spring",
  "ASP.NET",
  "Node.js",
  "Deno",
  "WebAssembly",
  "WebSockets",
  "PWA",
  "Service Workers",
  "Web Components",
  "JAMstack",
  "SSR",
  "GraphQL",
  "REST",
  "SOAP",
  "Microservices",
  "Serverless",
  "Responsive Design",
  "Cross-Browser Compatibility",
  "Accessibility",
  "SEO",
  "Web Performance",
  "Web Security",
  "OAuth",
  "JWT",
  "SSL/TLS",
  "CDN",
  "Web Scraping",
  "Web Crawling",
  "Headless CMS",
  "Static Site Generators",
  "Web Animation",
  "WebGL",
  "Three.js",
  "D3.js",
  "Chart.js",
  "Leaflet",
  "Mapbox",
  "Web Audio API",
  "WebRTC",
  "Web Sockets",
  "Web Workers",
  "IndexedDB",
  "LocalStorage",
  "Cookies",
  "Browser Extensions",

  // Mobile Development
  "Android",
  "iOS",
  "React Native",
  "Flutter",
  "Xamarin",
  "Ionic",
  "Cordova",
  "PhoneGap",
  "NativeScript",
  "Unity",
  "Unreal Engine",
  "Cocos2d",
  "SpriteKit",
  "ARKit",
  "ARCore",
  "Bluetooth",
  "NFC",
  "Geolocation",
  "Push Notifications",
  "In-App Purchases",
  "App Store Optimization",
  "Mobile Security",
  "Mobile Testing",
  "Cross-Platform Development",

  // Backend Development
  "API Design",
  "Authentication",
  "Authorization",
  "Database Design",
  "Caching",
  "Scalability",
  "Performance Optimization",
  "Load Balancing",
  "Message Queues",
  "WebSockets",
  "Serverless Architecture",
  "Microservices Architecture",
  "Monolithic Architecture",
  "Containers",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud",
  "Firebase",
  "Heroku",
  "DigitalOcean",
  "Nginx",
  "Apache",
  "IIS",
  "Monitoring",
  "Logging",
  "Debugging",
  "Profiling",
  "Continuous Integration",
  "Continuous Deployment",
  "DevOps",

  // Databases
  "SQL",
  "MySQL",
  "PostgreSQL",
  "Oracle",
  "SQL Server",
  "SQLite",
  "MongoDB",
  "Cassandra",
  "Redis",
  "Elasticsearch",
  "Neo4j",
  "CouchDB",
  "DynamoDB",
  "Firestore",
  "Realm",
  "Couchbase",
  "InfluxDB",
  "TimescaleDB",
  "Database Normalization",
  "Database Sharding",
  "Database Replication",
  "Database Partitioning",
  "Database Indexing",
  "Database Transactions",
  "ACID",
  "CAP Theorem",
  "ORM",
  "Query Optimization",

  // Data Science and Machine Learning
  "Data Analysis",
  "Data Visualization",
  "Statistics",
  "Probability",
  "Linear Algebra",
  "Calculus",
  "Regression",
  "Classification",
  "Clustering",
  "Neural Networks",
  "Deep Learning",
  "Convolutional Neural Networks (CNN)",
  "Recurrent Neural Networks (RNN)",
  "Generative Adversarial Networks (GAN)",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Reinforcement Learning",
  "Transfer Learning",
  "Unsupervised Learning",
  "Supervised Learning",
  "Semi-Supervised Learning",
  "Feature Engineering",
  "Dimensionality Reduction",
  "Anomaly Detection",
  "Recommender Systems",
  "Time Series Analysis",
  "Bayesian Inference",
  "Ensemble Methods",
  "Gradient Boosting",
  "Random Forests",
  "Support Vector Machines (SVM)",
  "K-Nearest Neighbors (KNN)",
  "Naive Bayes",
  "Principal Component Analysis (PCA)",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "scikit-learn",
  "numpy",
  "pandas",
  "matplotlib",
  "seaborn",
  "plotly",
  "bokeh",
  "Apache Spark",
  "Hadoop",
  "Hive",
  "Pig",
  "Kafka",
  "Storm",
  "Flink",
  "Airflow",
  "MLflow",
  "Kubeflow",
  "DataRobot",
  "Alteryx",
  "RapidMiner",
  "Weka",
  "KNIME",
  "OpenCV",
  "Tesseract OCR",
  "spaCy",
  "NLTK",
  "Gensim",
  "Hugging Face Transformers",

  // Software Engineering
  "Agile",
  "Scrum",
  "Kanban",
  "Waterfall",
  "Test-Driven Development (TDD)",
  "Behavior-Driven Development (BDD)",
  "Domain-Driven Design (DDD)",
  "SOLID Principles",
  "Design Patterns",
  "Architectural Patterns",
  "Microservices",
  "Monolithic Architecture",
  "Service-Oriented Architecture (SOA)",
  "Event-Driven Architecture",
  "Hexagonal Architecture",
  "Clean Architecture",
  "Layered Architecture",
  "MVC",
  "MVVM",
  "MVP",
  "Functional Programming",
  "Object-Oriented Programming (OOP)",
  "Procedural Programming",
  "Reactive Programming",
  "Declarative Programming",
  "Imperative Programming",
  "Concurrent Programming",
  "Parallel Programming",
  "Distributed Systems",
  "Cloud Computing",
  "Edge Computing",
  "Internet of Things (IoT)",
  "Embedded Systems",
  "Real-Time Systems",
  "High-Performance Computing",
  "Quantum Computing",
  "Blockchain",
  "Cryptography",
  "Cybersecurity",
  "Ethical Hacking",
  "Penetration Testing",
  "Vulnerability Assessment",
  "Threat Modeling",
  "Risk Management",
  "Compliance",
  "GDPR",
  "HIPAA",
  "PCI DSS",
  "SOC",
  "ISO 27001",
  "OWASP",
  "Secure Coding Practices",
  "Code Review",
  "Static Code Analysis",
  "Dynamic Code Analysis",
  "Fuzz Testing",
  "Mutation Testing",
  "A/B Testing",
  "Usability Testing",
  "Accessibility Testing",
  "Localization",
  "Internationalization",
  "Globalization",
  "User Experience (UX)",
  "User Interface (UI)",
  "Human-Computer Interaction (HCI)",
  "Interaction Design",
  "Information Architecture",
  "Wireframing",
  "Prototyping",
  "Mockups",
  "Style Guides",
  "Design Systems",
  "Atomic Design",
  "Responsive Design",
  "Mobile-First Design",
  "Progressive Enhancement",
  "Graceful Degradation",
  "Cross-Browser Compatibility",
  "Browser Automation",
  "Web Scraping",
  "Data Visualization",
  "Data Journalism",
  "Generative Art",
  "Creative Coding",
  "Algorithmic Art",
  "Procedural Generation",
  "Game Development",
  "Virtual Reality (VR)",
  "Augmented Reality (AR)",
  "Mixed Reality (MR)",
  "Computer Graphics",
  "Shaders",
  "Ray Tracing",
  "Physics Simulation",
  "Particle Systems",
  "Fluid Dynamics",
  "Cloth Simulation",
  "Procedural Animation",
  "Motion Capture",
  "Inverse Kinematics",
  "Rigging",
  "3D Modeling",
  "Texturing",
  "Lighting",
  "Rendering",
  "Compositing",
  "Visual Effects (VFX)",
  "Color Theory",
  "Typography",
  "Iconography",
  "Illustration",
  "Photography",
  "Videography",
  "Audio Engineering",
  "Music Production",
  "Sound Design",
  "Voice User Interfaces",
  "Chatbots",
  "Conversational AI",
  "Sentiment Analysis",
  "Text-to-Speech",
  "Speech Recognition",
  "Machine Translation",
  "Natural Language Understanding",
  "Knowledge Graphs",
  "Semantic Web",
  "Linked Data",
  "RDF",
  "OWL",
  "SPARQL",
  "Ontologies",
  "Taxonomies",
  "Thesauri",
  "Controlled Vocabularies",
  "Information Retrieval",
  "Search Engines",
  "Recommendation Engines",
  "Collaborative Filtering",
  "Content-Based Filtering",
  "Hybrid Recommender Systems",
  "Context-Aware Recommender Systems",
  "Explainable AI",
  "Interpretable AI",
  "Fairness in AI",
  "AI Ethics",
  "Privacy-Preserving AI",
  "Federated Learning",
  "Differential Privacy",
  "Homomorphic Encryption",
  "Secure Multi-Party Computation",
  "Zero-Knowledge Proofs",
  "Post-Quantum Cryptography",
  "Quantum-Resistant Cryptography",
  "Lattice-Based Cryptography",
  "Multivariate Cryptography",
  "Code-Based Cryptography",
  "Supersingular Isogeny Key Exchange",
  "Quantum Key Distribution",
  "Quantum Error Correction",
  "Quantum Algorithms",
  "Quantum Machine Learning",
  "Quantum Simulation",
  "Quantum Sensing",
  "Quantum Metrology",
  "Quantum Communication",
  "Quantum Networking",
  "Quantum Internet",
  "Quantum Computing Hardware",
  "Superconducting Qubits",
  "Trapped Ion Qubits",
  "Photonic Qubits",
  "Topological Qubits",
  "Quantum Dots",
  "Quantum Annealing",
  "Adiabatic Quantum Computation",
  "Variational Quantum Algorithms",
  "Quantum Approximate Optimization Algorithm (QAOA)",
  "Quantum Neural Networks",
  "Quantum Generative Models",
  "Quantum Reinforcement Learning",
  "Quantum Natural Language Processing",
  "Quantum Computer Vision",
  "Quantum Game Theory",
  "Quantum Finance",
  "Quantum Chemistry",
  "Quantum Biology",
  "Quantum Sensing for Healthcare",
  "Quantum-Enhanced Imaging",
  "Quantum-Enhanced Radar",
  "Quantum-Enhanced Lidar",
  "Quantum-Enhanced Microscopy",
  "Quantum-Enhanced Spectroscopy",
  "Quantum-Enhanced Magnetometry",
  "Quantum-Enhanced Gravimetry",
  "Quantum-Enhanced Clocks",
  "Quantum-Enhanced Positioning",
  "Quantum-Enhanced Navigation",
  "Quantum-Enhanced Sensing for Autonomous Vehicles",
  "Quantum-Enhanced Sensing for Robotics",
  "Quantum-Enhanced Sensing for Industrial Applications",
  "Quantum-Enhanced Sensing for Environmental Monitoring",
  "Quantum-Enhanced Sensing for Agriculture",
  "Quantum-Enhanced Sensing for Smart Cities",
  "Quantum-Enhanced Sensing for Defense and Security",
  "Quantum-Enhanced Sensing for Aerospace",
  "Quantum-Enhanced Sensing for Space Exploration",
  "Quantum-Enhanced Sensing for Fundamental Physics",
  "Quantum-Enhanced Sensing for Materials Science",
  "Quantum-Enhanced Sensing for Energy",
  "Quantum-Enhanced Sensing for Telecommunications",
  "Quantum-Enhanced Sensing for Media and Entertainment",
  "Quantum-Enhanced Sensing for Sports",
  "Quantum-Enhanced Sensing for Gaming",
  "Quantum-Enhanced Sensing for Education",
  "Quantum-Enhanced Sensing for Art and Culture",
  "Quantum-Enhanced Sensing for Social Good",

  // Tools and Frameworks
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "SVN",
  "Mercurial",
  "Jira",
  "Trello",
  "Asana",
  "Slack",
  "Microsoft Teams",
  "Zoom",
  "Skype",
  "Google Meet",
  "WebEx",
  "Visual Studio Code",
  "Sublime Text",
  "Atom",
  "IntelliJ IDEA",
  "PyCharm",
  "WebStorm",
  "Eclipse",
  "NetBeans",
  "Xcode",
  "Android Studio",
  "Unity",
  "Unreal Engine",
  "Blender",
  "Maya",
  "3ds Max",
  "ZBrush",
  "Houdini",
  "Nuke",
  "After Effects",
  "Premiere Pro",
  "Final Cut Pro",
  "DaVinci Resolve",
  "Audacity",
  "Pro Tools",
  "Ableton Live",
  "FL Studio",
  "Figma",
  "Sketch",
  "Adobe XD",
  "InVision",
  "Zeplin",
  "Balsamiq",
  "Axure",
  "Framer",
  "Origami Studio",
  "Principle",
  "Flinto",
  "Marvel",
  "Bootstrap",
  "Material-UI",
  "Ant Design",
  "Semantic UI",
  "Tailwind CSS",
  "Bulma",
  "UIkit",
  "Foundation",
  "Materialize",
  "Vuetify",
  "Buefy",
  "Quasar",
  "Ionic",
  "NativeScript",
  "Xamarin.Forms",
  "Flask",
  "FastAPI",
  "Bottle",
  "Pyramid",
  "Tornado",
  "aiohttp",
  "Sanic",
  "Vibora",
  "Responder",
  "Falcon",
  "Hug",
  "Eve",
  "Connexion",
  "Molten",
  "Morepath",
  "Zope",
  "Grok",
  "Nevow",
  "Twisted",
  "Cyclone",
  "Diesel",
  "Actix",
  "Rocket",
  "Tide",
  "Warp",
  "Hyper",
  "Tonic",
  "Tower",
  "Gotham",
  "Warp",
  "Actix Web",
  "Yew",
  "Seed",
  "Percy",
  "stdweb",
  "web-sys",
  "js-sys",
  "wasm-bindgen",
  "wasmer",
  "wasmtime",
  "lucet",
  "cranelift",
  "Futhark",
  "APL",
  "J",
  "K",
  "Q",
  "Nim",
  "Crystal",
  "D",
  "Zig",
  "V",
  "Pony",
  "Reason",
  "OCaml",
  "ReScript",
  "Elm",
  "PureScript",
  "Idris",
  "Agda",
  "Coq",
  "TLA+",
  "Alloy",
  "Z3",
  "Lean",
  "Isabelle",
  "Nix",
  "Dhall",
  "Unison",

  // Soft Skills and Methodologies
  "Communication",
  "Collaboration",
  "Teamwork",
  "Leadership",
  "Problem Solving",
  "Critical Thinking",
  "Creativity",
  "Innovation",
  "Adaptability",
  "Flexibility",
  "Time Management",
  "Organization",
  "Attention to Detail",
  "Analytical Skills",
  "Research Skills",
  "Presentation Skills",
  "Public Speaking",
  "Writing",
  "Technical Writing",
  "Documentation",
  "Mentoring",
  "Coaching",
  "Conflict Resolution",
  "Negotiation",
  "Empathy",
  "Emotional Intelligence",
  "Cultural Awareness",
  "Diversity and Inclusion",
  "Ethics",
  "Integrity",
  "Professionalism",
  "Responsibility",
  "Accountability",
  "Self-Motivation",
  "Initiative",
  "Proactivity",
  "Curiosity",
  "Lifelong Learning",
  "Growth Mindset",
  "Agile Methodologies",
  "Scrum",
  "Kanban",
  "Lean",
  "Six Sigma",
  "PMBOK",
  "Prince2",
  "ITIL",
  "COBIT",
  "Scaled Agile Framework (SAFe)",
  "Large-Scale Scrum (LeSS)",
  "Disciplined Agile Delivery (DAD)",
  "Extreme Programming (XP)",
  "Crystal",
  "Feature-Driven Development (FDD)",
  "Dynamic Systems Development Method (DSDM)",
  "Rapid Application Development (RAD)",
  "Spiral",
  "Waterfall",
  "V-Model",
  "Incremental",
  "Prototyping",
  "Cleanroom",
  "Rational Unified Process (RUP)",
  "Capability Maturity Model Integration (CMMI)",
  "ISO 9001",
  "ISO 12207",
  "ISO 15504",
  "SPICE",
  "Automotive SPICE",
  "Medical Device Software Development Lifecycle (IEC 62304)",
  "DO-178C (Software Considerations in Airborne Systems and Equipment Certification)",
  "MISRA C",
  "MISRA C++",
  "JSF++",
  "AUTOSAR",
  "SIL (Safety Integrity Level)",
  "IEC 61508",
  "ISO 26262",
  "EN 50128",
  "IEC 60880",
  "IEC 61513",
  "IEC 62061",
  "ISO 13849",
  "IEC 61131",
  "ISA-88",
  "ISA-95",
  "ISA-99 (IEC 62443)",
  "OWASP Top 10",
  "OWASP ASVS",
  "OWASP MASVS",
  "OWASP Testing Guide",
  "OWASP Code Review Guide",
  "OWASP Cheat Sheet Series",
  "OWASP Proactive Controls",
  "OWASP Risk Rating Methodology",
  "OWASP Software Assurance Maturity Model (SAMM)",
  "OWASP Internet of Things Top 10",
  "OWASP Serverless Top 10",
  "OWASP API Security Top 10",
  "OWASP Mobile Top 10",
  "OWASP Vulnerability Management Guide",
  "OWASP WSTG (Web Security Testing Guide)",
  "NIST Cybersecurity Framework",
  "NIST SP 800-53",
];
